# 1. Identificación y puerto del microservicio
spring.application.name=sales-service
server.port=8081

# 2. Configuración de la base de datos en memoria (H2)
spring.datasource.url=jdbc:h2:mem:salesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 3. Consola Web de H2 (para inspeccionar tablas visualmente)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 4. JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 5. Activación de Eureka Client
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.config.enabled=false

# ========================================================
# CONFIGURACION DE RESILIENCE4J CIRCUIT BREAKER
# ========================================================
# Tamano de la ventana de medicion (analiza las ultimas 5 peticiones)
resilience4j.circuitbreaker.instances.catalogService.sliding-window-size=5

# Porcentaje de fallo para abrir el circuito (50% de errores o mas)
resilience4j.circuitbreaker.instances.catalogService.failure-rate-threshold=50

# Tiempo que permanece ABIERTO antes de intentar reconectar (10 segundos)
resilience4j.circuitbreaker.instances.catalogService.wait-duration-in-open-state=10000ms

# Numero de peticiones de prueba en estado HALF-OPEN (semi-abierto)
resilience4j.circuitbreaker.instances.catalogService.permitted-number-of-calls-in-half-open-state=2

# Habilitar soporte para Feign
spring.cloud.openfeign.circuitbreaker.enabled=true